version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -w 1 --bind 0.0.0.0:8000 djangotest.wsgi"
    container_name: django-test
    volumes:
      - .:/django-test

  nginx:
    build: ./nginx
    container_name: docker-test
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./djangotest/static:/var/www/static/
